### ISSUE TITLE
Example HTML to include n amount in display

### ISSUE THREAD

**Issue by Jese44** [warrior25/HA-Nysse#4]
Hi! not really an issue but more of an featurish request.
I currently have the following on my card:

```
type: custom:html-template-card
ignore_line_breaks: true
content: >
  <style>.grid-container { display: grid;

   padding: 10px; } </style>

  <div style="font-size:24px", class="grid-container"><br>STOP N
  (to centre)</div> {% set departures =
  state_attr('sensor.keskisenkatu_1_1234, 'departures') %} 

  {% for i in range(0, departures | count, 1) %} <div style="display:grid;
  grid-template-columns: 2fr 1fr; font-size: 20px; padding: 10px 0px 0px 0px">
  <div><span style="border-style:solid;background:blue;border:2px solid white
  ">&nbsp{% if departures[i].line | int < 10 %} {{departures[i].line}}&nbsp {%
  else %}{{departures[i].line}}&nbsp{% endif %}</span>&nbsp &nbsp&nbsp {{
  departures[i].destination }}</div><div style="text-align: right">{% if
  departures[i].realtime %}<ha-icon style="color:#4ba97b; padding: 0px 10px 0px
  0px" icon="mdi:signal-variant"></ha-icon>{% endif %} {% if
  departures[i].time_to_station | int < 21  %} {{departures[i].time_to_station}}
  min {% else %}{{departures[i].departure}}{% endif %}</div></div>
   
  {% endfor %}
```

Different from your  card example it greates "nysse" themed box around the line number (tried with icons but numeric icons stop at "9". It's not perfect but does the job, kind of. shows the linenumber-destination-time(and live time). But I've really been trying to get n amount of stops into one single card but seems like its impossible? I'm no pro in HTML so this is why I'm opening issue since you got HTML knowledge among this projject! lets say keskustori A and keskustori B into same card somehow.

**Comment by warrior25** [comment]
@Jese44 Just to clarify, is your goal to have N amount of total departures collected from multiple stops or just departures from multiple stops displayed in a single card?

**Comment by Jese44** [comment]
Departures from multiple stops in single card (and sorted by time; closest bus by time no matter if it's from stop "1" or stop "2");

line 1 from stop 1    2min
line 2 from stop 1   3min
line 55 from stop 2   13:30
line 1 from stop 1     13:35
line 55 from stop 2   13:36
etc....

I don't know if this kind of diplay is possible on html (I Assume yes but my knowledge on HTML logic is limited) or not.

**Comment by warrior25** [comment]
This can be achieved by creating a new template sensor in your configuration.yaml

```
  - platform: template
    sensors:
      combined:
        value_template: "{{ states('sensor.stop1') }}"
        attribute_templates:
          departures: >-
            {% set combined_data = state_attr('sensor.stop1', 'departures') + state_attr('sensor.stop2', 'departures') %}
            {{ combined_data | sort(attribute='time_to_station') }}
```
Let me know if this works for you

**Comment by Jese44** [comment]
Hi, that's exactly what I was after, **huge thanks!**
here's my version for the frontend card (code(s) below):
![image](https://github.com/warrior25/HA-Nysse/assets/45014337/c8a04a08-7ad6-4ca0-9134-926619aefd8e)


```
type: custom:html-template-card
ignore_line_breaks: true
content: >
  <style>.grid-container { display: grid;

   padding: 10px; } </style>

  <div style="font-size:24px", class="grid-container"><br> Keskustaan</div> {%
  set departures = state_attr('sensor.combined_buses', 'departures') %} 

  {% for i in range(0, departures | count, 1) %} <div style="display:grid;
  grid-template-columns: 2fr 1fr; font-size: 20px; padding: 10px 0px 0px 0px">
  <div><span style="border-style:solid;background:blue;border:2px solid white
  ">&nbsp{% if departures[i].line | int < 10 %} {{departures[i].line}}&nbsp {%
  else %}{{departures[i].line}}&nbsp{% endif %}</span>&nbsp &nbsp&nbsp {{
  departures[i].destination }}</div><div style="text-align: right">{% if
  departures[i].realtime %}<ha-icon style="color:#4ba97b; padding: 0px 10px 0px
  0px" icon="mdi:signal-variant"></ha-icon>{% endif %} {% if
  departures[i].time_to_station | int < 21  %} {{departures[i].time_to_station}}
  min {% else %}{{departures[i].departure}}{% endif %}</div></div>
   
  {% endfor %}
```

And slightly modified yours (changed sensor name*):
```
- platform: template
  sensors:
      combined_buses:
        value_template: "{{ states('sensor.stop1') }}" 
        attribute_templates:
          departures: >-
            {% set combined_data = state_attr('sensor.stop1', 'departures') + state_attr('sensor.stop2', 'departures') %}
            {{ combined_data | sort(attribute='time_to_station') }}
      
```      
...for future if I happen to move to a location near the tram stops I or someone should create logic to change line number color to refer whether it's a bus or a tram (red base and black text for tram, blue base white text for Nysses buses for example). 
This should be pretty easy to do since tram and bus line numbers are not overlapping!: if linenumber == 3 || 1 --> color red/black else blue/white.
